apiVersion: v1
kind: Deployment
metadata:
  name: backend-Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-Deployment
  template:
    metadata:
      labels:
        app: backend-Deployment
    spec:
      containers:
      - name: backend
        image: back
        ports:
        - containerPort: 4002